import { SessionProvider } from 'next-auth/react'
import { yekanBakh, kahroba } from '@/fonts/fonts'
import { auth } from '@/security/auth'
import '@/styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await auth()
  
  // بررسی نقش کاربر
  if (!session || session.user.role !== 1) {
    return <div className={styles.unauthorized}>دسترسی غیرمجاز</div>
  }

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`${kahroba.variable} ${yekanBakh.variable}`}>{children}</body>
      </html>
    </SessionProvider>
  )
}
